apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: vaanah-dev
  name: vaanah-app-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    # alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /app
            backend:
              serviceName: service-vaanah-app
              servicePort: 80